version: '3'

services:
  keycloak:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak:/opt/keycloak/standalone/configuration
      - ./themes:/opt/keycloak/themes